#Fill sample details here
samples:
    test1: test1.sorted.bam

ppqualpath: ./phantompeakqualtools/run_spp.R
#Parameters for peak calling using macs2

broad_peak: ""

treatment: -t

control: -c

macs_optional: ""

